version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: my_api_app
    container_name: api_app
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - books

  web:
    image: nginx
    container_name: nginx
    ports:
      - "${API_PORT:-8000}:80"  
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/snippets:/etc/nginx/snippets
    depends_on:
      - app
    networks:
      - books

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root_password}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-laravel}" 
      MYSQL_USER: "${MYSQL_USER:-laravel_user}" 
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-laravel_password}"  
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306" 
    networks:
      - books

volumes:
  db_data:

networks:
  books: